"""Workspace entry point. Auto-generated by restful."""
import sys
from pathlib import Path

# Add workspace root to sys.path so 'from apis.x import endpoints' works
sys.path.insert(0, str(Path(__file__).parent))
